Sald19
nerdify/instafake-front-end pull request #10
Opened 2020-11-04 14:11 UTC by sald19

2020-11-04 14:53 UTC, calonzolg requested changes

2020-11-04 14:53 UTC, calonzolg commented on src/pages/Post/Post.tsx
> +  console.log(comments)
borrar console log

2020-11-04 15:03 UTC, calonzolg approved these changes

2020-11-04 15:38 UTC, claushellsing approved these changes
LGTM

2020-11-05 15:30 UTC, Fernando-Larios approved these changes

2020-11-14 15:01 UTC, merged